dist: trusty
sudo: false

language: node_js
node_js:
  - "8"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - npm install

jobs:
  include:
  # - stage: lint
  #   script:
  #   - ng lint
  # - stage: test
  #   script:
  #   - npm run test:lib-coverage
  #   - npm run report-coverage:lib
  - stage: build & publish showcase
    script:
    - npm run build:showcase
    deploy:
      provider: pages
      skip_cleanup: true
      github_token: 91866943adc520b1dd509c9b79ae08ea3b1aa35f
      local_dir: dist/dynamic-table-showcase
    if: branch = master
  # - stage: build & publish lib
  #   script:
  #   - npm run build:lib
  #   - npm run publish:lib
  #   if: branch = master